name: Golang Formatter
on:
  pull_request:
    types: [opened, review_requested, ready_for_review]

jobs:
  build:
    name: Golang Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Golang Formatter
        uses: rvarbanov/auto-go-format@patch-1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
