name: Golang Formatter
on:
  pull_request:
    types: [opened, review_requested, ready_for_review]

jobs:
  build:
    name: Golang Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Golang Formatter
        uses: shubham030/auto-go-format@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
